# Generated by Django 6.0.6 on 2026-07-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pc', 'PC Completo'), ('console', 'Console'), ('peripheral', 'Periférico'), ('hardware', 'Hardware/Componente'), ('game', 'Jogo'), ('accessory', 'Acessório')], default='hardware', max_length=20),
        ),
    ]
